package com.example.englishapp.core.database.entity;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.Objects;

@Entity(tableName = "story")
public class StoryEntity {

    @PrimaryKey(autoGenerate = true)
    private long storyId;

    @NonNull
    private String title;

    @NonNull
    private String content; // JSON string generated by AI (Chuỗi JSON sinh ra từ AI)

    @NonNull
    private String difficulty;

    private long createdAt;

    public StoryEntity(long storyId, @NonNull String title, @NonNull String content,
                       @NonNull String difficulty, long createdAt) {
        this.storyId = storyId;
        this.title = title;
        this.content = content;
        this.difficulty = difficulty;
        this.createdAt = createdAt;
    }

    // Convenience constructor with defaults
    @Ignore
    public StoryEntity(@NonNull String title, @NonNull String content, @NonNull String difficulty) {
        this(0, title, content, difficulty, System.currentTimeMillis());
    }

    // Getters
    public long getStoryId() { return storyId; }
    @NonNull public String getTitle() { return title; }
    @NonNull public String getContent() { return content; }
    @NonNull public String getDifficulty() { return difficulty; }
    public long getCreatedAt() { return createdAt; }

    // Setters
    public void setStoryId(long storyId) { this.storyId = storyId; }
    public void setTitle(@NonNull String title) { this.title = title; }
    public void setContent(@NonNull String content) { this.content = content; }
    public void setDifficulty(@NonNull String difficulty) { this.difficulty = difficulty; }
    public void setCreatedAt(long createdAt) { this.createdAt = createdAt; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StoryEntity that = (StoryEntity) o;
        return storyId == that.storyId
                && createdAt == that.createdAt
                && Objects.equals(title, that.title)
                && Objects.equals(content, that.content)
                && Objects.equals(difficulty, that.difficulty);
    }

    @Override
    public int hashCode() {
        return Objects.hash(storyId, title, content, difficulty, createdAt);
    }

    @NonNull
    @Override
    public String toString() {
        return "StoryEntity{" +
                "storyId=" + storyId +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", difficulty='" + difficulty + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
